### ISSUE TITLE
在Kitex中无法使用Frugal功能

### ISSUE THREAD

**Issue by damon008** [cloudwego/frugal#18]
Env
- Kitex：0.4.2

利用kitex根据IDL生成代码
```
kitex -module "xxx" -thrift frugal_tag,template=slim -service xxx idl/xxx.thrift
```
这里使用的是不需要编解码代码，生成了代码

但在初始化 client 和 server 时使用 WithPayloadCodec(thrift.NewThriftFrugalCodec())，发现无法引入FrugalWrite、FrugalRead

![屏幕快照 2022-10-31 上午11 39 43](https://user-images.githubusercontent.com/25023599/198929033-487634de-178a-4f01-8312-c0e2e804a1a4.png)

**Comment by simon0-o** [comment]
如果是 amd64 的 macos 、 linux 的话，是已知问题，会在下个版本修复，可以先用下分支 `go get github.com/cloudwego/kitex@fix_frugal_build_tag_main`。如果是 arm 的机器，或者是 windows 的话，目前还不支持 frugal。

**Comment by simon0-o** [comment]
最新版本已修复
