### ISSUE TITLE
add support for go1.20

### ISSUE THREAD

**Issue by jiajun-c** [cloudwego/frugal#22]
When use the kitex with go1.20 I encountered the following problems , I hope there will be support for go 1.20 soon
```shell
# github.com/cloudwego/frugal/internal/loader
../../../../go/pkg/mod/github.com/cloudwego/frugal@v0.1.3/internal/loader/funcdata.go:32:22: undefined: _ModuleData
../../../../go/pkg/mod/github.com/cloudwego/frugal@v0.1.3/internal/loader/funcdata.go:35:27: undefined: _ModuleData
../../../../go/pkg/mod/github.com/cloudwego/frugal@v0.1.3/internal/loader/funcdata.go:39:16: undefined: _ModuleData
../../../../go/pkg/mod/github.com/cloudwego/frugal@v0.1.3/internal/loader/funcdata.go:75:26: undefined: _ModuleData
../../../../go/pkg/mod/github.com/cloudwego/frugal@v0.1.3/internal/loader/funcdata_invalid.go:27:9: panic("Unsupported Go version. Supported versions are: 1.15, 1.16, 1.17, 1.18, 1.19") (no value) used as value
```

**Comment by felix021** [comment]
Thanks for you feedback. The support for go 1.20 is under development now.

**Comment by xieyh11** [comment]
What's the progress of supporting to go 1.20? Is there a possibility to support new version at go rc stage?

**Comment by felix021** [comment]
@xieyh11 should be ready next wwek. And for new versions of go, we'll support before release.

**Comment by chenzhuoyu** [comment]
@xieyh11 @jiajun-c Support for Go 1.20 was added in [this](https://github.com/cloudwego/frugal/commit/9786556b59a7c372f241a61b7461162f047004d1) commit.
