### ISSUE TITLE
readme 有疑问

### ISSUE THREAD

**Issue by R2coding2run** [cloudwego/frugal#26]
无需生成代码的意思是什么
我理解直接通过idl就可以调用接口，可示例让我感觉很不清楚
可以增加一些示例么  
无需生成 kitex_gen 么 我看示例也有引用呀
还是 将 kitex_gen换成 thriftgo生成的代码呢
可以给一些清楚的示例 仅转换了一个结构体 我没看懂 如何 无需生成代码

**Comment by felix021** [comment]
是指无需生成「用于编/解码 Thrift binary 的 Go 代码」（在运行时通过 JIT 的方式生成机器码），但仍然需要生成对应的 Struct
