### ISSUE TITLE
Unlicensed dependency: `github.com/chenzhuoyu/iasm`

### ISSUE THREAD

**Issue by berndverst** [cloudwego/frugal#27]
**Describe the bug**

Your dependency `github.com/chenzhuoyu/iasm` is unlicensed. As a result `cloudwego/frugal` cannot be used in MIT / Apache 2 licensed projects.

Please update `github.com/chenzhuoyu/iasm` to `v0.9.0` which added a license. Then create a new release.

Please also update `cloudwego/kitex` and other projects to use the new `cloudwego/frugal` release with the updated dependency.

谢谢
Bernd, Maintainer of Dapr (dapr.io) -- github.com/dapr

**Comment by felix021** [comment]
Thanks, we've updated the dependency and released v0.1.7
