### ISSUE TITLE
go 1.21 support

### ISSUE THREAD

**Issue by xieyh11** [cloudwego/frugal#29]
why not support it in rc cycle? or add a default slow support for outter version

**Comment by felix021** [comment]
Sorry that the support of go1.21 is not rolled out for now.

As of go1.21rc2, we've noticed that go1.21 introduces a breaking change in the `runtime.gcWriteBarrier`, which make the support harder than previous version.

We first adapted [sonic](https://github.com/bytedance/sonic/pull/493) as it's more widely used.

Also we'll soon release a new version of Kitex to [skip frugal on go1.21](https://github.com/cloudwego/kitex/pull/1012) as a fallback.

We'll be working on frugal soon.
