### ISSUE TITLE
[GLCC 赛题] SSA 后端 Auto-vectorization Pass 的实现

### ISSUE THREAD

**Issue by cloudwegoIce** [cloudwego/frugal#5]
**🚩GLCC 高校编程夏令营赛题**
👏欢迎大家参与～
> GLCC 是由中国计算机学会举办的高校开源编程夏令营活动，活动为项目准备了开源奖学金。请在以下链接中报名参与⬇️
>报名链接： [https://www.gitlink.org.cn/glcc/subjects/detail/161](https://www.gitlink.org.cn/glcc/subjects/detail/161)
>关于issue相关问题、解题思路的答疑将在群内进行
<img width="197" alt="image" src="https://user-images.githubusercontent.com/104130938/170914107-081c4538-6e89-4f04-9720-bf5ba9e473be.png">

1、题目描述
Frugal 是字节自研的一款高性能 Thrift 库，旨在使用 JIT 技术来加速 Thrift 的编解码过程。由于 Thrift 采用了大端序，而 x86_64 等常见的处理器架构均为小端序，因此对于 list<i32> 这一类的数据类型需要一个循环来实现小端到大端的转换。而这个过程如果能够利用 SIMD 指令的话，可以极大的提高性能。

2、编码任务
- 实现一个 SSA 后端的 Auto-vectorization Pass
- 输入原始的 CFG，输出 vectorize 之后的 CFG
- IR 表示形式使用 Frugal SSA IR (internal/atm/ssa 目录)
- 该 Pass 的运行顺序在 Fusion 之后，在 Final TDCE 之前
- CPU 架构为 x86_64，SIMD 指令使用 AVX / AVX-2 指令集

3、技能要求和编程语言
- 编译原理
- x86_64 指令集知识
- 实现语言为 Go

4、预期完成结果
- 能够识别并且将 CFG 中的 load-swap-store 循环替换为正确的 SIMD 指令

**Comment by GuangmingLuo** [comment]
Project Closure
