### ISSUE TITLE
frugal field type not provided will cause panic

### ISSUE THREAD

**Issue by yunwei37** [cloudwego/frugal#8]
## Produce

If I simply run the examples in the `Serialization and deserialization on a customized Go struct` section in README.md, it will get an error message:

```
panic: frugal: cannot measure encoded size: invalid tag for field main.MyStruct.Msg

goroutine 1 [running]:
github.com/cloudwego/frugal/internal/binary/encoder.EncodedSize({0xf714e0, 0xc00010f620})
        /home/yunwei/coding/frugal/internal/binary/encoder/encoder.go:69 +0x8e
github.com/cloudwego/frugal.EncodedSize(...)
        /home/yunwei/coding/frugal/frugal.go:27
main.main()
        /home/yunwei/coding/frugal/cmd/main.go:20 +0xa9
exit status 2
```

the test code is like this, which is copied from README:

```go
package main

import (
    "github.com/cloudwego/frugal"
)

type MyStruct struct {
    Msg     string  `frugal:"1,default"`
    Code    int64   `frugal:"2,default"`
    Numbers []int64 `frugal:"3,default,list<i64>"`
}

func main() {
    ms := &MyStruct{
        Msg: "my message",
        Code: 1024,
        Numbers: []int64{0, 1, 2, 3, 4},
    }

    buf := make([]byte, frugal.EncodedSize(ms))
    frugal.EncodeObject(buf, nil, ms)

    got := &MyStruct{}
    frugal.DecodeObject(buf, got)
}
```

However, if I change the struct to:

```go
type MyStruct struct {
    Msg     string  `frugal:"1,default,string"`
    Code    int64   `frugal:"2,default,i64"`
    Numbers []int64 `frugal:"3,default,list<i64>"`
}
```

Then the example can be run successfully.

## Question

The README said:

> Frugal tag is like `frugal:"1,default,string"`, `1` is field ID, `default` is field requiredness, `string` is field type. Field ID and requiredness is always required, but field type is only required for `list`, `set` and `enum`.

while the code in the `internal/binary/defs/resolver.go` gives that:

```go
        /* must have 3 fields: ID, Requiredness, Type */
        if ft = strings.Split(tv, ","); len(ft) != 3 {
            return nil, fmt.Errorf("invalid tag for field %s.%s", vt, sf.Name)
        }
```

Is the `field type` optional tag not support currently, or the tag should be provided each time in Frugal? 

By the way, another minor fix for README example is in PR #7 .

**Comment by yunwei37** [comment]
明白啦，谢谢您！

**Comment by GuangmingLuo** [comment]
@chenzhuoyu 这个问题优化了吗？如果已经完成麻烦更新下 issue 状态

**Comment by chenzhuoyu** [comment]
@GuangmingLuo 没有，非阻塞低优问题，现阶段懒得修
