### ISSUE TITLE
Support go1.19

### ISSUE THREAD

**Issue by feilengcui008** [cloudwego/frugal#9]
**Is your feature request related to a problem? Please describe.**

Compiling using go1.19 will failed with the following messages:
../../../../go/pkg/mod/github.com/cloudwego/frugal@v0.1.1/internal/loader/funcdata_invalid.go:27:9: panic("Unsupported Go version. Supported versions are: 1.15, 1.16, 1.17, 1.18") (no value) used as value

**Describe the solution you'd like**
support compile using go1.19

**Describe alternatives you've considered**

**Additional context**

**Comment by xieyh11** [comment]
when to merge?
